### ISSUE TITLE
进程退出，panic err

### ISSUE THREAD

**Issue by wangsijia1985** [zr-hebo/sniffer-agent#23]
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
github.com/zr-hebo/sniffer-agent/exporter.NewKafkaExporter(0xa9d750)
        /export/project/golang/src/github.com/zr-hebo/sniffer-agent/exporter/kafka.go:83 +0x329
github.com/zr-hebo/sniffer-agent/exporter.NewExporter(0xc00018feb8, 0x512d9b)
        /export/project/golang/src/github.com/zr-hebo/sniffer-agent/exporter/model.go:26 +0x8c
main.mainServer()
        /export/project/golang/src/github.com/zr-hebo/sniffer-agent/main.go:50 +0x34
main.main()
        /export/project/golang/src/github.com/zr-hebo/sniffer-agent/main.go:46 +0x9a

**Comment by zr-hebo** [comment]
这个是 Kafka服务不可用，连接报错吧？

**Comment by Johnny-Three** [comment]
hi 思佳
